### ISSUE TITLE
ERROR: logging before flag.Parse

### ISSUE THREAD

**Issue by yxxyun** [rubblelabs/tx#14]
when I submit payment,got this error message
ERROR: logging before flag.Parse: I0415 13:40:38.141115    4712 remote.go:41] wss://s-east.ripple.com:443
my command:tx -s=ssssssssss -q=xxx -t p -d=rxxxxxx  -a=xxxxxx

**Comment by donovanhide** [comment]
Yep, I get the same when I `go get -u github.com/rubblelabs/tx`. Seems to be because of this patch to glog:

https://github.com/golang/glog/commit/65d674618f712aa808a7d0104131b9206fc3d5ad

Which shows how long it is since I did the last `go get` :-)

The message is harmless and the tx will still go through if valid. The issue is that the ripple package shouldn't really be logging anything. I'll look at this in the near future.
